name: RPGCraftTable
main: com.outlook.schooluniformsama.RPGCraftTable
version: 0.0.5
author: School_Uniform
commands:
  rpgct:
      description: RPGCraftTable Help
      usage: /<command>
permissions: 
  RPGCraftTable.admin:
    description: Use Admin's Commands
    default: op